ALTER TABLE SECTION ADD (FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number));
ALTER TABLE GRADE_REPORT ADD (FOREIGN KEY (Student_number) REFERENCES STUDENT(Student_number));
ALTER TABLE GRADE_REPORT ADD (FOREIGN KEY(Section_identifier) REFERENCES SECTION(Section_identifier));
ALTER TABLE PREREQUISITE ADD (FOREIGN KEY(Course_number) REFERENCES COURSE(Course_number));
ALTER TABLE PREREQUISITE ADD (FOREIGN KEY(Prerequisite_number) REFERENCES COURSE(Course_number));
