DROP TABLE PREREQUISITE CASCADE CONSTRAINTS;
DROP TABLE GRADE_REPORT CASCADE CONSTRAINTS;
DROP TABLE SECTION CASCADE CONSTRAINTS;
DROP TABLE COURSE CASCADE CONSTRAINTS;
DROP TABLE STUDENT CASCADE CONSTRAINTS;